### ISSUE TITLE
Lapses ignored with Queue controller

### ISSUE THREAD

**Issue by zer0xs** [lovac42/HoochieBaby#9]
I use this addon because I use the a 1440 interval with new cards and want them mixed in with young/mature cards. Currently using the V1 scheduler. 

When I do my reviews and miss a card, I should see the card again in 10 min, however, the Queue controller currently ignores this and pulls the card within just a few cards (within a minute sometimes). Is there anyway to enforce the steps in lapses? Maybe I'm missing something?

**Comment by lovac42** [comment]
I'm not sure what you are getting at. The Queue controller doesn't control 10 min cards, as described in detail in the documentation. Perhaps you are talking about the "Learn ahead limits" in preferences that is part of Anki?

**Comment by zer0xs** [comment]
Ok, so setting "Learn ahead limit" to 0 from 30 minutes fixes the behavior. However, I still think this is a bug since the default anki behavior will only use the "learn ahead" limit when there are no other cards available. 

What I think happens (please correct me if I'm wrong) is that the extension will try to pull from learning cards, and because "missed" cards now fall within the learn ahead limit, anki doesn't try to stop the extension from pulling the card, allowing the card to be pulled early. So perhaps something can be added to force the extension to prevent this, instead of relying on anki to lock the card?

**Comment by lovac42** [comment]
Still I am not really following you. Anki has multiple types of learning cards, not just one type. But the reason handling 10m cards are left out of this addon is because it requires patching into Anki in multiple places. And there are major differences between V1, V2 and 2.0. So not dealing with them was the right choice at the time. But as we move forward and V2 becomes the standard, I might look at it again.

So whatever problem you maybe trying to describe is the intended effect to get around those limits. But feel free to play around with it and see if you can fix it.
